services:
  mongo_commande:
    image: mongo:6
    container_name: mongo_db_commande
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db

  mongo_menu:
   image: mongo:6
   container_name: mongo_db_menu
   ports:
      - "27018:27017"
  #  volumes:
  #     - mongo_data:/data/db

  mongo_utilisateur:
    image: mongo:6
    container_name: mongo_db_utilisateur
    ports:
      - "27019:27017"
    # volumes:
    #   - mongo_data:/data/db 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      
  commande_app:
    build: ./commande
    container_name: commande_app
    volumes:
      - .:/usr/src/app 
    ports:
      - "3001:3000"
    environment:
      - MONGO_URI=mongodb://mongo_commande:27017/db_commande
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - mongo_commande
      - rabbitmq

  menu_app:
    build: ./menu
    container_name: menu_app
    volumes:
      - .:/usr/src/app 
    ports:
      - "3002:3000"
    environment:
      - MONGO_URI=mongodb://mongo_menu:27017/db_menu
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - mongo_menu
      - rabbitmq

  utilisateur_app:
    build: ./utilisateur
    container_name: utilisateur_app
    volumes:
      - .:/usr/src/app 
    ports:
      - "3003:3000"
    environment:
      - MONGO_URI=mongodb://mongo_utilisateur:27017/db_utilisateur
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - JWT_SECRET=dfgbdfgnbdfdbn
    depends_on:
      - mongo_utilisateur
      - rabbitmq

  # firefox:
  #   container_name: firefox
  #   image: jlesage/firefox
  #   ports:
  #     - 5800:5800
  #   volumes:
  #     - firefox:/config
  
volumes:
  mongo_data:
  firefox: